### ISSUE TITLE
Segfault with origin/master

### ISSUE THREAD

**Issue by levaidaniel** [conformal/spectrwm#118]
Hi!

Good to see some developments here :) Let me report a little mishap right away ;)

I get a coredump on Linux with the latest checkout:

```
GNU gdb (GDB) 7.11
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-slackware-linux".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /usr/slackbuilds/tmp/spectrwm-dev/linux/spectrwm...done.
[New LWP 1581]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
Core was generated by `/usr/slackbuilds/tmp/spectrwm-dev/linux/spectrwm'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x000000000040de07 in stack (r=0x6b63616c62) at ../spectrwm.c:4937
4937            g = r->g;
(gdb) #0  0x000000000040de07 in stack (r=0x6b63616c62) at ../spectrwm.c:4937
#1  0x000000000041ccdb in screenchange (e=0x7d28c0) at ../spectrwm.c:11579
#2  0x000000000041dee2 in event_handle (evt=0x7d28c0) at ../spectrwm.c:11967
#3  0x000000000041e4c8 in main (argc=1, argv=0x7ffe0eabdef8) at ../spectrwm.c:12134
(gdb) #0  0x000000000040de07 in stack (r=0x6b63616c62) at ../spectrwm.c:4937
        g = {x = 0, y = 4, w = 7906948, h = 0}
        r_prev = 0x0
        val = {10485787, 0}
#1  0x000000000041ccdb in screenchange (e=0x7d28c0) at ../spectrwm.c:11579
        r = 0x6b63616c62
        i = 1
        num_screens = 1
#2  0x000000000041dee2 in event_handle (evt=0x7d28c0) at ../spectrwm.c:11967
        type = 88 'X'
#3  0x000000000041e4c8 in main (argc=1, argv=0x7ffe0eabdef8) at ../spectrwm.c:12134
        pfd = {{fd = 3, events = 1, revents = 1}, {fd = 0, events = 1, revents = 0}}
        sact = {__sigaction_handler = {sa_handler = 0x407291 <sighdlr>, sa_sigaction = 0x407291 <sighdlr>}, sa_mask =
        sb = {st_dev = 140729144564992, st_ino = 140212048049602, st_nlink = 1008, st_mode = 246144264, st_uid = 32766
          st_size = 114, st_blksize = 16384, st_blocks = 140729144565056, st_atim = {tv_sec = 6443336, tv_nsec = 42141
            tv_nsec = 0}, __glibc_reserved = {140212076287814, 1, 0}}
        pwd = 0x7f85a9856e20 <resbuf.10110>
        r = 0x0
        evt = 0x7d28c0
        xfd = 3
        i = 1
        num_screens = 1
        num_readable = 1
        conf = "\000etc/scrotwm.conf\000otwm.conf\000\000\177\000\000\300\312\035\253\205\177\000\000\032\000\000\000\
        cfile = 0x0
        stdin_ready = false
        startup = false
(gdb) 4932                      return;
4933
4934            DNPRINTF(SWM_D_STACK, "stack: begin\n");
4935
4936            /* Adjust stack area for region bar and padding. */
4937            g = r->g;
4938            g.x += region_padding;
4939            g.y += region_padding;
4940            g.w -= 2 * border_width + 2 * region_padding;
4941            g.h -= 2 * border_width + 2 * region_padding;
(gdb) quit
```

Also I didn't bother fiddling with my _~/.spectrwm.conf_, I just removed it.
I have two screens, plus the laptop's display, but the latter is off. Here's xrandr's output:

```
Screen 0: minimum 8 x 8, current 3840 x 1080, maximum 32767 x 32767
eDP1 connected (normal left inverted right x axis y axis)
   1600x900      60.04 +  40.03
   1368x768      60.00
   1280x720      60.00
   1024x768      60.00
   1024x576      60.00
   960x540       60.00
   800x600       60.32    56.25
   864x486       60.00
   800x450       60.00
   640x480       59.94
   720x405       60.00
   640x360       60.00
DP1 disconnected (normal left inverted right x axis y axis)
DP1-1 connected primary 1920x1080+0+0 (normal left inverted right x axis y axis) 509mm x 286mm
   1920x1080     60.00*+
   1600x900      60.00
   1280x1024     75.02    60.02
   1152x864      75.00
   1024x768      75.08    60.00
   800x600       75.00    60.32
   640x480       75.00    60.00
   720x400       70.08
DP1-2 connected 1920x1080+1920+0 (normal left inverted right x axis y axis) 509mm x 286mm
   1920x1080     60.00*+
   1600x900      60.00
   1280x1024     75.02    60.02
   1152x864      75.00
   1024x768      75.08    60.00
   800x600       75.00    60.32
   640x480       75.00    60.00
   720x400       70.08
DP1-3 disconnected (normal left inverted right x axis y axis)
HDMI1 disconnected (normal left inverted right x axis y axis)
HDMI2 disconnected (normal left inverted right x axis y axis)
VIRTUAL1 disconnected (normal left inverted right x axis y axis)
```

**Comment by LordReg** [comment]
Thanks for the report!
