### ISSUE TITLE
infinite loop and core dump with stacked/fullscreen windows

### ISSUE THREAD

**Issue by nick-owens-eero** [conformal/spectrwm#513]
similar to #333, spectrwm hangs and then segfaults after overflowing its stack with about 200,000 frames. in this instance, it was firefox and gnome-terminal overlapping, but in the past it happened with xterm too.

backtrace (many frames elided):
```
#199321 0x000055ff2075be79 in mapnotify (e=0x55ff20bd8ed0) at ../spectrwm.c:12339
#199322 0x000055ff2075f866 in event_handle (evt=0x55ff20bd8ed0) at ../spectrwm.c:13711
#199323 0x000055ff20741a0d in event_drain (rt=0x0) at ../spectrwm.c:1587
#199324 0x000055ff20741a55 in focus_flush () at ../spectrwm.c:1599
#199325 0x000055ff2075be79 in mapnotify (e=0x55ff20bd8e30) at ../spectrwm.c:12339
#199326 0x000055ff2075f866 in event_handle (evt=0x55ff20bd8e30) at ../spectrwm.c:13711
#199327 0x000055ff20741a0d in event_drain (rt=0x0) at ../spectrwm.c:1587
#199328 0x000055ff20741a55 in focus_flush () at ../spectrwm.c:1599
#199329 0x000055ff2075bba7 in enternotify (e=0x55ff20bd8ca0) at ../spectrwm.c:12223
#199330 0x000055ff2075f811 in event_handle (evt=0x55ff20bd8ca0) at ../spectrwm.c:13697
#199331 0x000055ff20741a0d in event_drain (rt=0x0) at ../spectrwm.c:1587
#199332 0x000055ff20741a55 in focus_flush () at ../spectrwm.c:1599
#199333 0x000055ff2075be79 in mapnotify (e=0x55ff20bd8c50) at ../spectrwm.c:12339
#199334 0x000055ff2075f866 in event_handle (evt=0x55ff20bd8c50) at ../spectrwm.c:13711                                                                                        #199335 0x000055ff20741a0d in event_drain (rt=0x0) at ../spectrwm.c:1587
#199336 0x000055ff20741a55 in focus_flush () at ../spectrwm.c:1599
#199337 0x000055ff2075bba7 in enternotify (e=0x55ff20bd8540) at ../spectrwm.c:12223
#199338 0x000055ff2075f811 in event_handle (evt=0x55ff20bd8540) at ../spectrwm.c:13697
#199339 0x000055ff20741a0d in event_drain (rt=0x0) at ../spectrwm.c:1587
#199340 0x000055ff20741a55 in focus_flush () at ../spectrwm.c:1599
#199341 0x000055ff2075bba7 in enternotify (e=0x55ff20ba43f0) at ../spectrwm.c:12223
#199342 0x000055ff2075f811 in event_handle (evt=0x55ff20ba43f0) at ../spectrwm.c:13697
#199343 0x000055ff20741a0d in event_drain (rt=0x0) at ../spectrwm.c:1587
#199344 0x000055ff20741a55 in focus_flush () at ../spectrwm.c:1599
#199345 0x000055ff2075bba7 in enternotify (e=0x55ff20ba4270) at ../spectrwm.c:12223
#199346 0x000055ff2075f811 in event_handle (evt=0x55ff20ba4270) at ../spectrwm.c:13697
#199347 0x000055ff20741a0d in event_drain (rt=0x0) at ../spectrwm.c:1587
#199348 0x000055ff20741a55 in focus_flush () at ../spectrwm.c:1599
#199349 0x000055ff2075c6b0 in unmapnotify (e=0x55ff20ba4310) at ../spectrwm.c:12644
#199350 0x000055ff2075f8ba in event_handle (evt=0x55ff20ba4310) at ../spectrwm.c:13722
#199351 0x000055ff20741a0d in event_drain (rt=0x0) at ../spectrwm.c:1587
#199352 0x000055ff20741a55 in focus_flush () at ../spectrwm.c:1599
#199353 0x000055ff2074c7e0 in switchlayout (bp=0x55ff20abca40, r=0x55ff20abccc0, args=0x55ff209674f8 <actions+216>) at ../spectrwm.c:5903
#199354 0x000055ff2075adea in keypress (e=0x55ff20ba42c0) at ../spectrwm.c:11579
#199355 0x000055ff2075f844 in event_handle (evt=0x55ff20ba42c0) at ../spectrwm.c:13705
#199356 0x000055ff2075ff15 in main (argc=0x1, argv=0x7ffd8ea4d738) at ../spectrwm.c:13897
```

this occurred on 60b2076bacbc7214223f6c34390c244fb1978fb2, but i don't think anything changed in master since then has addressed this issue.

**Comment by nick-owens-eero** [comment]
system is Ubuntu 20.04.5 LTS, full stack and spectrwm config attached.

[spectrwm.conf.txt](https://github.com/conformal/spectrwm/files/10298754/spectrwm.conf.txt)

[stack.txt](https://github.com/conformal/spectrwm/files/10298753/stack.txt)

**Comment by LordReg** [comment]
Fix is in master now, closing, but please verify all is good on your system.

**Comment by nick-owens-eero** [comment]
thanks for the quick response! i don't have a trivial reproducer, but i'll update and keep on hacking :shipit:
